# scratch: scratch.cpp
	# g++ scratch.cpp -o scratch  -Wall -Wextra -pedantic -std=c++11
	# ./scratch
	# rm scratch

graph: graph.c
	gcc graph.c -o graph -g  -Wall -Wextra -pedantic -std=c17
	./graph
