day4: day4.cpp
	g++ day4.cpp -o day4  -Wall -Wextra -pedantic -std=c++17
	./day4
	rm day4

# scratchc: scratch.c
	# gcc scratch.c -o scratchc  -Wall -Wextra -pedantic -std=c17
	# ./scratchc
	# rm scratchc

