scratch: scratch.cpp
	g++ scratch.cpp -o scratch  -Wall -Wextra -pedantic -std=c++17
	./scratch
	rm scratch

# scratchc: scratch.c
	# gcc scratch.c -o scratchc  -Wall -Wextra -pedantic -std=c17
	# ./scratchc
	# rm scratchc
