# scratch: scratch.cpp
	# g++ scratch.cpp -o scratch  -Wall -Wextra -pedantic -std=c++11
	# ./scratch
	# rm scratch

scratch: scratch.c
	gcc scratch.c -o scratch -g  -Wall -Wextra -pedantic -std=c17
	./scratch
