day2: day2.cpp
	g++ day2.cpp -o day2  -Wall -Wextra -pedantic -std=c++17
	./day2
	rm day2

# scratchc: scratch.c
	# gcc scratch.c -o scratchc  -Wall -Wextra -pedantic -std=c17
	# ./scratchc
	# rm scratchc

