day1: day1.cpp
	g++ day1.cpp -o day1  -Wall -Wextra -pedantic -std=c++17
	./day1
	rm day1

# scratchc: scratch.c
	# gcc scratch.c -o scratchc  -Wall -Wextra -pedantic -std=c17
	# ./scratchc
	# rm scratchc

